---
abstract: 'Cairo backend for Graphics::Primitive'
author:
  - 'Cory G Watson <gphat@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  File::Spec: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Graphics-Primitive-Driver-Cairo
no_index:
  directory:
    - inc
    - t
requires:
  Cairo: 1.061
  Geometry::Primitive: 0.13
  Graphics::Primitive: 0.45
  IO::File: 0
  Math::Complex: 1.56
  Moose: 0.76
  Text::Flow: 0.01
resources:
  license: http://dev.perl.org/licenses/
version: 0.42
