---
abstract: 'Cairo backend for Graphics::Primitive'
author:
  - 'Cory G Watson <gphat@cpan.org>'
build_requires:
  Graphics::Color::RGB: 0
  Graphics::Primitive::Font: 0
  Test::More: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300001, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Graphics-Primitive-Driver-Cairo
requires:
  Cairo: 0
  Carp: 0
  Geometry::Primitive::Point: 0
  Geometry::Primitive::Rectangle: 0
  Graphics::Primitive::Driver: 0
  Graphics::Primitive::Driver::TextLayout: 0
  Graphics::Primitive::TextBox: 0
  IO::File: 0
  Math::Trig: 0
  Moose: 0
  Moose::Util::TypeConstraints: 0
  Text::Flow: 0
resources:
  homepage: https://github.com/gphat/graphics-primitive-driver-cairo
  repository: https://github.com/gphat/graphics-primitive-driver-cairo.git
version: 0.44
